version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App 2"
    links:
      - db
    ports:
    - "5000:5000"


  db:
    image: mysql:5.7
    container_name: "MySql_Database"
    ports:
    - "3200:3200"
    environment:
      MYSQL_ROOT_PASSWORD:  root
    volumes:
    - ./db:/docker-entrypoint-initdb.d/:ro